apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "exec"
  name: "sipin-pg-webhook-events-dispatcher"
  labels:
    app: "sipin-pg-webhook-events-dispatcher"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "sipin-pg-webhook-events-dispatcher-${env}"
      namespace: "sipin"
      labels:
        app: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/component: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/instance: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/name: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/part-of: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "sipin-pg-webhook-events-dispatcher"
        env: ${env}
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "sipin-pg-webhook-events-dispatcher-${env}"
      namespace: "sipin"
      labels:
        app: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/component: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/instance: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/name: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/part-of: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "sipin-pg-webhook-events-dispatcher"
          env: ${env}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "sipin-pg-webhook-events-dispatcher"
            deploymentconfig: "sipin-pg-webhook-events-dispatcher-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "sipin-pg-webhook-events-dispatcher-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "sipin-pg-webhook-events-dispatcher-${env}"
                - secretRef:
                    name: "sipin-pg-webhook-events-dispatcher-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/sipin/sipin-pg-webhook-events-dispatcher:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "sipin-pg-webhook-events-dispatcher-${env}"
      namespace: "sipin"
      labels:
        app: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/component: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/instance: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/name: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/part-of: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      DB_HOST: ''
      DB_PORT: ''
      DB_NAME: ''
      SVIX_BASE_URL: ''
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "sipin-pg-webhook-events-dispatcher-${env}"
      namespace: "sipin"
      labels:
        app: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/component: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/instance: "sipin-pg-webhook-events-dispatcher-${env}"
        app.kubernetes.io/name: "sipin-pg-webhook-events-dispatcher"
        app.kubernetes.io/part-of: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime: "sipin-pg-webhook-events-dispatcher"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      DB_USERNAME: ''
      DB_PASSWORD: ''
      SVIX_AUTH_TOKEN: ''
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"